In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("~/oh_textmining/Batch_4009282_batch_results.csv")
df.head()

HITId                       HITTypeId  \
0  3QO7EE372O05JQQOZ9UH1022BYTBQM  3CM00QMEUL0OM2EY9JIV3PQMT8T6WO   
1  3QO7EE372O05JQQOZ9UH1022BYTBQM  3CM00QMEUL0OM2EY9JIV3PQMT8T6WO   
2  3QO7EE372O05JQQOZ9UH1022BYTBQM  3CM00QMEUL0OM2EY9JIV3PQMT8T6WO   
3  3QHITW7OYOM00GLWTVUL6PIWTG7QA5  3CM00QMEUL0OM2EY9JIV3PQMT8T6WO   
4  3QHITW7OYOM00GLWTVUL6PIWTG7QA5  3CM00QMEUL0OM2EY9JIV3PQMT8T6WO   

                                  Title  \
0  Sentiment analysis for News Articles   
1  Sentiment analysis for News Articles   
2  Sentiment analysis for News Articles   
3  Sentiment analysis for News Articles   
4  Sentiment analysis for News Articles   

                                         Description         Keywords Reward  \
0  Each entry is a sentence from a news article, ...  sentiment, text  $0.10   
1  Each entry is a sentence from a news article, ...  sentiment, text  $0.10   
2  Each entry is a sentence from a news article, ...  sentiment, text  $0.10   
3  Each entry is a sentence from a news article, ...  sentiment, text  $0.10   
4  Each entry is a sentence from a news article, ...  sentiment, text  $0.10   

                   CreationTime  MaxAssignments  \
0  Sat Apr 25 03:19:59 PDT 2020               3   
1  Sat Apr 25 03:19:59 PDT 2020               3   
2  Sat Apr 25 03:19:59 PDT 2020               3   
3  Sat Apr 25 03:19:33 PDT 2020               3   
4  Sat Apr 25 03:19:33 PDT 2020               3   

                                RequesterAnnotation  \
0  BatchId:4009282;OriginalHitTemplateId:928390909;   
1  BatchId:4009282;OriginalHitTemplateId:928390909;   
2  BatchId:4009282;OriginalHitTemplateId:928390909;   
3  BatchId:4009282;OriginalHitTemplateId:928390909;   
4  BatchId:4009282;OriginalHitTemplateId:928390909;   

   AssignmentDurationInSeconds  ...    RejectionTime RequesterFeedback  \
0                         3600  ...              NaN               NaN   
1                         3600  ...              NaN               NaN   
2                         3600  ...              NaN               NaN   
3                         3600  ...              NaN               NaN   
4                         3600  ...              NaN               NaN   

   WorkTimeInSeconds  LifetimeApprovalRate Last30DaysApprovalRate  \
0                158      100% (4837/4837)       100% (4837/4837)   
1                544      100% (2968/2968)       100% (2968/2968)   
2                 27        100% (338/338)         100% (338/338)   
3                273      100% (4837/4837)       100% (4837/4837)   
4                253      100% (2968/2968)       100% (2968/2968)   

  Last7DaysApprovalRate                                         Input.text  \
0      100% (4825/4825)  Underdogs don't just make for good Hollywood m...   
1      100% (2858/2858)  Underdogs don't just make for good Hollywood m...   
2        100% (318/318)  Underdogs don't just make for good Hollywood m...   
3      100% (4825/4825)  For example, designers LightCollab have fashio...   
4      100% (2858/2858)  For example, designers LightCollab have fashio...   

  Answer.sentiment.label Approve Reject  
0               Positive     NaN    NaN  
1               Positive     NaN    NaN  
2                Neutral     NaN    NaN  
3               Positive     NaN    NaN  
4               Positive     NaN    NaN  

[5 rows x 31 columns]

In [6]:
df.columns

Index(['HITId', 'HITTypeId', 'Title', 'Description', 'Keywords', 'Reward',
       'CreationTime', 'MaxAssignments', 'RequesterAnnotation',
       'AssignmentDurationInSeconds', 'AutoApprovalDelayInSeconds',
       'Expiration', 'NumberOfSimilarHITs', 'LifetimeInSeconds',
       'AssignmentId', 'WorkerId', 'AssignmentStatus', 'AcceptTime',
       'SubmitTime', 'AutoApprovalTime', 'ApprovalTime', 'RejectionTime',
       'RequesterFeedback', 'WorkTimeInSeconds', 'LifetimeApprovalRate',
       'Last30DaysApprovalRate', 'Last7DaysApprovalRate', 'Input.text',
       'Answer.sentiment.label', 'Approve', 'Reject'],
      dtype='object')

In [7]:
df = df[['AssignmentId','Input.text','WorkerId','Answer.sentiment.label']]
df.head()

AssignmentId  \
0  340UGXU9DZEF6HT5B1AO1XOOZ1TVUG   
1  3QECW5O0KIEJ8AZ15521S38N308T56   
2  3R0T90IZ1TP02QMA0FQ27QZ85P7GCH   
3  345LHZDEDY5VU8RMRR4II2W58HYU3G   
4  36V4Q8R5ZLD4O1SFG0PS408M5POMQ2   

                                          Input.text        WorkerId  \
0  Underdogs don't just make for good Hollywood m...  A2YYQJ3JWA2KGD   
1  Underdogs don't just make for good Hollywood m...   AURYD2FH3FUOQ   
2  Underdogs don't just make for good Hollywood m...  A2EOOF9D135HQ1   
3  For example, designers LightCollab have fashio...  A2YYQJ3JWA2KGD   
4  For example, designers LightCollab have fashio...   AURYD2FH3FUOQ   

  Answer.sentiment.label  
0               Positive  
1               Positive  
2                Neutral  
3               Positive  
4               Positive

In [8]:
# number of unique workers
df['WorkerId'].nunique()

13

### Convert sentiment scores

In [9]:
def get_nss(x):
    if x=="Positive":
        return 3
    elif x=="Neutral":
        return 2
    elif x=="Negative":
        return 1
    elif x=="Very Positive":
        return 4
    elif x=="Very Negative":
        return 0
    else: return None

df["sentiment_score"] = df['Answer.sentiment.label'].apply(lambda x: get_nss(str(x)))

In [10]:
data = pd.DataFrame()

def get_data(dataf):
    dataf = dataf.reset_index(drop=True)
#     dic = {'text':dataf['Input.text'][0], "W1":dataf['Answer.sentiment.label'][0], "W2":dataf['Answer.sentiment.label'][1], \
#                         "W3":dataf['Answer.sentiment.label'][2]}
    dic = {'text':dataf['Input.text'][0], "W1":dataf['sentiment_score'][0], "W2":dataf['sentiment_score'][1], \
                        "W3":dataf['sentiment_score'][2]}
    return dic

dfg = df.groupby(['Input.text']).apply(lambda x: get_data(x)).reset_index(drop=True)
dfg.head()

0    {'text': ' SINGAPORE - A popular burger chain ...
1    {'text': '"(In some cases) the wife had to be ...
2    {'text': '"(Kon Chun) was a very good guy and ...
3    {'text': '", see what happens if you give an h...
4    {'text': '"A cat cafe might not be the best pl...
dtype: object

In [11]:
for i in dfg.index:
    data = data.append(dfg.loc[i,], ignore_index=True)
data.head()

W1   W2   W3                                               text
0  2.0  4.0  4.0   SINGAPORE - A popular burger chain from Ameri...
1  0.0  1.0  0.0  "(In some cases) the wife had to be taken to t...
2  3.0  3.0  4.0  "(Kon Chun) was a very good guy and everyone i...
3  2.0  2.0  2.0  ", see what happens if you give an honest answer.
4  2.0  3.0  3.0  "A cat cafe might not be the best place for a ...

In [12]:
print(len(data.index))

4846


# Cronbach's Alpha

In [13]:
def CronbachAlpha(itemscores):
    itemscores = np.asarray(itemscores)
    print(itemscores)
    itemvars = itemscores.var(axis=0, ddof=1)
    tscores = itemscores.sum(axis=1)
    nitems = itemscores.shape[1]

    return (nitems / (nitems-1)) * (1 - (itemvars.sum() / tscores.var(ddof=1)))

In [14]:
ca = CronbachAlpha(data[['W1','W2','W3']])
ca

[[2. 4. 4.]
 [0. 1. 0.]
 [3. 3. 4.]
 ...
 [2. 2. 2.]
 [1. 2. 2.]
 [2. 2. 2.]]


0.7326982606514421

In [16]:
data.to_csv("cronbach_alpha_data.csv",index=None)